### ISSUE TITLE
Sony Xperia Z2 Tablet isn't recognized

### ISSUE THREAD

**Issue by WildS0ft** [42SK/TVKILL#16]
My Sony Xperia Z2 Tablet isn't recognized by the app. "No IR blaster" which I'm pretty sure its got. The tablet even comes with an universal remote control app.

**Device:** Sony Xperia Z2 Tablet (SGP511)
**Android:** 5.1.1
**Firmware:** 23.4.A.1.264

**Comment by 42SK** [comment]
First of all, thanks a lot for reporting this.
When TV KILL sends IR codes, it usually uses the `ConsumerIrManager` class from the standard Android API.
Sony seems to be one of the companies that did not implement this class properly, therefore  TV KILL cannot find (or use) the IR blaster on your device.
However, Sony seems to provide [a custom IR API](https://developer.sony.com/develop/smartphones-and-tablets/camera-add-on-small-apps-or-ir-remote-apis/about/ir-remote-api/), which we might be able to use to transmit IR codes from devices like yours.
Have you found any other third party IR remote Apps so far that work on the Xperia Z2?

**Comment by WildS0ft** [comment]
Sorry for my very late reply. As far as I can tell you must indeed use Sony's own API to get access to the IR-blaster on Xperia devices. Although, they seem to have a lot of documentation on how to use it.

For example:
[Camera add-on small apps or IR-remote APIS](https://developer.sony.com/develop/archived-sdks/camera-add-on-small-apps-or-ir-remote-apis/)
[How to add IR-remote API support to your app](http://developer.sonymobile.com/knowledge-base/tutorials/xperia-phones-features/how-to-add-ir-remote-api-support-to-your-app/)

I haven't really messed around with any other IR apps apart from Sony's own Universal remote control, which seems to be working as it should.

EDIT: I just tested 3 random universal remote control apps from the Play store. None of them worked and none of them gave me any error messages. On one app I found (which I didn't test) it specifically said it didn't support Sony devices, however the ones I tested said nothing about it.

It would be awesome if you have the ability to implement Sony's own API to this app =)

**Comment by 42SK** [comment]
I just had a more thorough look at the documentation of the API.
It seems that Sony does not actually allow any third party apps to transmit custom IR codes. The API can only be used to send codes from a preinstalled database, which won't do us any good since **TV KILL** uses its own IR codes. Thus, I'm afraid that (at least for now) there is simply no way for **TV KILL** - or any of the other remote control apps you found - to work on Sony devices.

**Comment by WildS0ft** [comment]
Well that sucks. But thanks for looking into it anyway. At least now I, and everyone else with a Sony device, knows what to expect =) (Perhaps issue some kind of warning in the description or in the app itself).

If I get another device in the future with IR-compatibility I'm sure to check out this project again, or if it somehow down the line is made possible to work around these issues.

Thanks again for your time.
