### ISSUE TITLE
GPG release signing

### ISSUE THREAD

**Issue by NeverMine17** [42SK/TVKILL#21]
How about a GPG key for this project?
Also good to add this in `README.md`
```markdown
## Our GPG key
You can get public key from [here]( Link to key )
```
### EDIT:
Also how about X.509 key to sign apk?

**Comment by 42SK** [comment]
Android APKs usually have to be singed with a public-key certificate.
All the *.apk files on the [releases page](https://github.com/42SK/TVKILL/releases) are simply singed with the same certificate as the ones on Google Play.
(See https://source.android.com/security/apksigning/index.html for more information on APK signing)

**Comment by NeverMine17** [comment]
@42SK, Ok then. How about GPG?

**Comment by 42SK** [comment]
Since this project is neither very large nor important, I sincerely doubt that anyone will actually find a reasonable need to verify one of the release signatures. However, I'll look into it, maybe we can eventually start signing releases.
