### ISSUE TITLE
How about mute widget?

### ISSUE THREAD

**Issue by NeverMine17** [42SK/TVKILL#24]
It's should look like this:

![mute](https://cloud.githubusercontent.com/assets/23419131/22210136/4220de5c-e1a2-11e6-88bf-34b54cbadbb9.png)

**Comment by 42SK** [comment]
What exactly do you mean by "mute gadget"?
Are you perhaps referring to a widget?

**Comment by NeverMine17** [comment]
@42SK, Oops typo.
Yes, I’m talking about widget.
