### ISSUE TITLE
On my oneplus one TVKILL is broken on F droid. 

### ISSUE THREAD

**Issue by LifeIsStrange** [42SK/TVKILL#3]
I see the app on F droid but without the possibility of download. 
How can I give you a screenshot ?

**Comment by 42SK** [comment]
The OnePlus One is not equipped with a build-in infrared blaster.
F-Droid probably won't let you install TV KILL, since your phone does not fulfill the necessary hardware requirements.

**Comment by LifeIsStrange** [comment]
Now I understund thank you so much and sorry to have take your time :)
