### ISSUE TITLE
"No IR blaster" even though phone does have one.

### ISSUE THREAD

**Issue by MesteMonokrom** [42SK/TVKILL#32]
I'm using a LG G2 Mini (D620/D620r/G2M), which does have an IR blaster.

Is this a hardware limitation or is it down to not having a phone to debug with? Either way, let me know if there's anything I can do to help. I wouldn't know where to start personally, but I can be guided through things.

**Comment by NeverMine17** [comment]
As @42SK (owner of this project) previously said in issue #10:

> ...I had already heard of some LG devices that don't allow third party apps to transmit IR patterns, but I wasn't sure which devices are affected by this.
> I don't think that there's much we can do programmatically to solve this issue, since LG seems to have intentionally locked down the IR blaster on the VS980.
> However, there might be a way to bypass these restrictions.
> The most plausible solution I can think of would be to install CyanogenMod on your device (see issue #6 for more information). I cant guarantee that that will solve the problem, but it's definitely worth a try.

**Comment by 42SK** [comment]
@MesteMonokrom
There seem to be some LG devices that simply don't allow third party apps to access the IR blaster (see issue #10). Hence, I'm afraid there's not much you can do to help. But thanks for the offer!
